version: 2

sources:
  - name: medical
    database: "{{ env_var('DB_NAME', 'medical_warehouse') }}"
    schema: raw
    tables:
      - name: telegram_messages
        description: Raw telegram messages loaded from JSON files.
      - name: image_detections
        description: YOLOv8 detection results.
